Fix for RazorTemplateBase.Write/WriteTo overloads breaking with CS0311
RazorTemplateBase.Write & WriteTo  generic overloads meant to avoid
boxing were too wide in scope and broke compilation with error CS0311,
e.g.:

HelperTestTemplate.cshtml(28, 8): error CS0311: The type
'System.Web.WebPages.HelperResult' cannot be used as type parameter 'T'
in the generic type or method
'RazorGenerator.Templating.RazorTemplateBase.Write<T>(T)'. There is no
implicit reference conversion from 'System.Web.WebPages.HelperResult' to
'System.IConvertible'.

Write and WriteTo overloads are now scoped for most common types.